language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=2.0.1
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO_VERSION=2.0.1
  fast_finish: true

install:
  - pip install Django==$DJANGO_VERSION djangorestframework==3.7.7
  - pip install coverage==3.7.1
  - pip install coveralls
script:
  coverage run runtests.py
after_success:
  coveralls
